apiVersion: v1
data:
  bindPassword: RE1FMzVYTXgxY29wbzQucmVfcmU3OGd0ci1icnRlLEVX
kind: Secret
metadata:
  name: ldap-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: Opaque
