apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: openshift-logging
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: openshift-operators-redhat
spec: {}
status: {}

