apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
spec:
  source: bpm-catalog
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-product
  sourceNamespace: openshift-marketplace

