apiVersion: v1
kind: Namespace
metadata:
  name: prova1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitoring
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: default
spec:
  egress:
  - to:
      cidrSelector: 10.101.143.121/32
    type: Allow
  - to:
      cidrSelector: 10.101.143.122/32
    type: Allow
  - to:
      cidrSelector: 10.101.143.123/32
    type: Allow
  - to:
      cidrSelector: 0.0.0.0/0
    type: Deny
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-consumption
spec:
  hard:
    persistentvolumeclaims: "5"
    requests.storage: 100Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    limits.cpu: "8"
    limits.ephemeral-storage: 40Gi
    limits.memory: 16Gi
    requests.cpu: "4"
    requests.ephemeral-storage: 20Gi
    requests.memory: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: project-limits
spec:
  limits:
  - default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 500Mi
    type: Container
