apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: {{ .Values.global.name }}
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: {{ .Values.global.size.name }}
  namespace: {{ .Values.global.name }}
spec:
  hard:
    cpu: {{ .Values.global.size.cpu }} 
    memory: {{ .Values.global.size.memory }}
    limits.cpu: {{ .Values.global.size.limits.cpu }}
    limits.memory: {{ .Values.global.size.limits.memory }}
status: {}
